services:
  - type: web
    name: sayman-faucet
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: API_BASE
        value: https://sayman-validator.onrender.com/api
      - key: FAUCET_PORT
        value: 10000
      - key: FAUCET_AMOUNT
        value: 100
      - key: NODE_ENV
        value: production
    healthCheckPath: /health